name: Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7
        with:
          submodules: recursive

      - name: Install MinGW and CMake
        run: |
          sudo apt-get -o Acquire::ForceIPv4=true update
          sudo DEBIAN_FRONTEND=noninteractive apt-get -o Acquire::ForceIPv4=true install -y mingw-w64 cmake ninja-build

      - name: Bootstrap vcpkg
        run: |
          cd vcpkg
          ./bootstrap-vcpkg.sh -disableMetrics

      - name: Configure CMake
        run: |
          cmake -B build -G Ninja \
                -DCMAKE_TOOLCHAIN_FILE=vcpkg/scripts/buildsystems/vcpkg.cmake \
                -DVCPKG_TARGET_TRIPLET=x64-mingw-static \
                -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_SYSTEM_NAME=Windows \
                -DCMAKE_C_COMPILER=x86_64-w64-mingw32-gcc \
                -DCMAKE_CXX_COMPILER=x86_64-w64-mingw32-g++ \
                -DCMAKE_RC_COMPILER=x86_64-w64-mingw32-windres

      - name: Build
        run: cmake --build build -j$(nproc)

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: built-binaries
          path: |
            build/bin/trainer.dll
            build/bin/PG3D_Injector.exe
